spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://${MYSQL_HOST}:3306/cola_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver