server:
  port: 8180
spring:
  application:
    name: code-generator
  freemarker:
    template-loader-path: classpath:/
unique-prefix: AbcDeF
output-dir: D:\JavaProjects\micro-service-cola\generator-output\
