spring:
# Data source config
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cola_dev?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
# Redis config
  data:
    redis:
      database: 0
      host: ${REDIS_HOST:localhost}
      port: 6379
      #      password: 123456
      timeout: 100ms
      connectTimeout: 5s
      clientName: ${spring.application.name}
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
  #      cluster:
  #        nodes:
  #      sentinel:
  #        master:
  #        nodes:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: ${ROCKET_MQ_HOST:127.0.0.1}:9876
          group: ${spring.application.name}
#      bindings:
#        sendTestMessage-out-0:
#          destination: test-topic

# Spring boot actuator
management:
  endpoints:
    enabled-by-default: on
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    defaults:
      enabled: on
user:
  name: erpang
