server:
  port: 8084
spring:
  profiles:
    active: local
  config:
    import: classpath:datasource-${spring.profiles.active}.yaml
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
