server:
  port: 8084
spring:
  profiles:
    active: local
  application:
    name: micro-service-cola
  cloud:
    nacos:
      discovery:
        namespace: ${NACOS_DISCOVERY_NAMESPACE:55d4d35b-9d91-4f55-aa17-27f13862d697}
        group: ${NACOS_DISCOVERY_GROUP:micro-service-cola}
        server-addr: ${NACOS_HOST:localhost}:8848
      config:
        namespace: ${NACOS_CONFIG_NAMESPACE:55d4d35b-9d91-4f55-aa17-27f13862d697}
        group: ${NACOS_CONFIG_GROUP:micro-service-cola}
        server-addr: ${NACOS_HOST:localhost}:8848
        refresh-enabled: true
  config:
    import: optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: info
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.erpang.scaffold.web
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn