spring:
  data:
    redis:
      database: 0
      host: ${REDIS_HOST}
      port: 6379
      #      password: 123456
      timeout: 100ms
      connectTimeout: 5s
      clientName: local-dev
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 8
          # 连接池中的最大空闲连接 默认 8
          max-idle: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
          max-wait: -1
          # 连接池中的最小空闲连接 默认 0
          min-idle: 0
  #      cluster:
  #        nodes:
  #      sentinel:
  #        master:
  #        nodes: